### ISSUE TITLE
Switch for non-evil user

### ISSUE THREAD

**Issue by RickFreemanCui** [willbchang/teem-emacs#3]
Is it possible to add a switch to disable the evil mode for non-evil users? Is it as simple as commenting the (use-package evil) statement or are there any packages that depend on the evil mode itself?

**Comment by weierz** [comment]
You can simply delete the **Vim Emulator** section as well as **evil-pinyin** and **ace-pinyin**.

<img width="921" alt="image" src="https://github.com/willbchang/ward-emacs/assets/14329786/05ca352b-6ad3-4d3e-b9bf-017c69032319">
